server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 9091
database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password:
  url: jdbc:mysql://localhost:3306/contact_api